# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.5'

networks:
  corp:
    driver: bridge

services:
  raventest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raventest
    networks:
      - corp
    environment:
      - version=1
      - dbreset=true
      - dbname=RavenTest.sqlite
      - rdbname=iiRdb
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
      - ASPNETCORE_ENVIRONMENT=Production
    #   - ASPNETCORE_Kestrel__Certificates__Default__Password=Visvis10
    #   - ASPNETCORE_Kestrel__Certificates__Default__Path=/secure/dev_cert.pfx
    volumes:
      - /app/secure:/secure:ro
    ports:
      - '5051:5051'
      - '5051:5051'
      - '5000:5000'
      - '443:443'
 