FROM mcr.microsoft.com/dotnet/sdk:5.0.12-focal AS base
# COPY --from=mcr.microsoft.com/dotnet/aspnet:5.0.12-focal-amd64 /usr/share/dotnet /usr/share/dotnet
WORKDIR /app
EXPOSE 443
EXPOSE 8080

# Creates a non-root user with an explicit UID and adds permission to access the /app folder
# For more info, please refer to https://aka.ms/vscode-docker-dotnet-configure-containers
RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

FROM mcr.microsoft.com/dotnet/sdk:5.0.12-focal AS build
# COPY --from=mcr.microsoft.com/dotnet/aspnet:5.0.12-focal-amd64 /usr/share/dotnet /usr/share/dotnet
WORKDIR /src
COPY ["RavenTestApi.csproj", "./"]
RUN dotnet restore "RavenTestApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "RavenTestApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RavenTestApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RavenTestApi.dll"]